title: >- 
  Game Development Society,<br />
  IIT Kanpur
email: #
description: >- # this means to ignore newlines until "baseurl:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: #
github_username:  gamedev-iitk

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
